# Generated by Django 4.2 on 2023-04-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdata',
            options={'verbose_name': 'customerData', 'verbose_name_plural': 'customerDatas'},
        ),
    ]
