# Generated by Django 4.2.1 on 2023-05-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customerdata_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdata",
            name="profileimg",
            field=models.ImageField(upload_to="media/sellerprofile/"),
        ),
    ]
