# Generated by Django 4.1.7 on 2023-03-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecom_seller_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('countrycode', models.CharField(max_length=4)),
                ('phone', models.CharField(max_length=12)),
                ('profile_img', models.ImageField(upload_to='media/seller_prof')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.ecom_seller')),
            ],
        ),
    ]
