# Generated by Django 4.1.7 on 2023-03-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecom_category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('catg_name', models.CharField(max_length=20)),
                ('createdon', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ecom_products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product_images', models.ImageField(default='', upload_to='media/productimg')),
                ('category_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.ecom_category')),
            ],
        ),
        migrations.CreateModel(
            name='ecom_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatg_name', models.CharField(default='', max_length=50)),
                ('crearedon', models.DateTimeField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ecom_category')),
            ],
        ),
        migrations.CreateModel(
            name='ecom_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('comments', models.CharField(max_length=250)),
                ('postedon', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ecom_products')),
            ],
        ),
        migrations.AddField(
            model_name='ecom_products',
            name='subcategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ecom_subcategory'),
        ),
        migrations.CreateModel(
            name='ecom_productDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('small_description', models.CharField(max_length=150)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ecom_products')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.ecom_seller')),
            ],
        ),
    ]
