# Generated by Django 4.1.7 on 2023-03-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ek_category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('catg_name', models.CharField(max_length=150)),
                ('createdon', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ek_products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('prod_image', models.URLField()),
                ('catg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ek_category')),
            ],
        ),
        migrations.CreateModel(
            name='ek_subcategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subcatg_name', models.CharField(max_length=150)),
                ('createdon', models.DateTimeField()),
                ('catg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ek_category')),
            ],
        ),
        migrations.CreateModel(
            name='ek_products_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_images', models.ImageField(upload_to='product_images')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ek_products')),
            ],
        ),
        migrations.CreateModel(
            name='ek_products_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_description', models.CharField(max_length=1500)),
                ('prod_smalldescription', models.CharField(max_length=150)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ek_products')),
            ],
        ),
        migrations.AddField(
            model_name='ek_products',
            name='subcatg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ek_subcategory'),
        ),
    ]
