# Generated by Django 4.2.1 on 2023-05-03 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/productimg')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimg', to='products.product')),
            ],
        ),
    ]
