# Generated by Django 4.2.1 on 2023-05-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_rename_productimages_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="media/productimg/itemimage/"),
        ),
    ]
